version: '3.8'
services:
  db:
    image: postgres:15.4-alpine
    restart: always
    networks:
      - "network"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="${PG_ADM_PASS}"
    ports:
      - '5432:5432'

    volumes:
      - type: bind
        source: /media/willusb/pgdata
        target: /var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.labels.postgres==true]
    
  adminer:
      image: adminer
      networks:
        - "network"
        - "ingress_traefik_external"
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`adminer.akselerasjon.no`)"
        - "traefik.http.routers.adminer.entrypoints=websecure"
        - "traefik.http.routers.adminer.tls.certresolver=myresolver"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.auth.basicauth.users=user:${BASIC_AUTH_PW}"


networks:
  network:
  ingress_traefik_external:
    external: true
volumes:
  postgres:
