version: '3.8'
services:    
  web:
      image: ghcr.io/askasp/unified-health:latest-arm64
      networks:
        - "net"
        - "ingress_traefik_external"
      restart: always
      
      env_file:
        - .env
      
      deploy: 
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.unified_health.rule=Host(`uh.akselerasjon.no`)"
          - "traefik.http.routers.unified_health.entrypoints=websecure"
          - "traefik.http.routers.unified_health.tls.certresolver=myresolver"
          - "traefik.http.services.unified_health.loadbalancer.server.port=3000"
        placement:      
          constraints:
            - node.labels.worker == true

      
  db:
      image: postgres:15-alpine
      env_file:
        - .env
      networks:
        - "net"
      volumes:
        - type: bind
          source: /media/willusb/unified-health-data
          target: /var/lib/postgresql/data
        
      deploy: 
        placement:      
          constraints:
            - node.labels.role == persistent_storage_1
      restart: always
      # healthcheck:
      #   test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      #   interval: 5s
      #   timeout: 5s
      #   retries: 5
volumes:
  umami-db-data:


networks:
  net:
  ingress_traefik_external:
    external: true

