version: '3.8'
services:    
  web:
      image: ghcr.io/askasp/unified-health:latest-arm64
      env_file:
      - .env
      networks:
        - "postgres_network"
        - "ingress_traefik_external"
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.unified_health.rule=Host(`uh.akselerasjon.no`)"
        - "traefik.http.routers.unified_health.entrypoints=websecure"
        - "traefik.http.routers.unified_health.tls.certresolver=myresolver"
        - "traefik.http.services.unified_health.loadbalancer.server.port=3000"


networks:
  postgres_network:
    external: true
  ingress_traefik_external:
    external: true

