version: '3'
services:
  web:
    image: ghcr.io/umami-software/umami:postgresql-latest

    networks:
      - "postgres_network"
      - "ingress_traefik_external"

    env_file:
    - .env

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`umami.akselerasjon.no`)"
      - "traefik.http.routers.umami.entrypoints=websecure"
      - "traefik.http.routers.umami.tls.certresolver=myresolver"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"


networks:
  postgres_network:
    external: true
  ingress_traefik_external:
    external: true
